version: '3'
services: 
  db-mysql:
   container_name: db-mysql
   image: mysql/mysql-server:5.7
   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
   environment:
    MYSQL_DATABASE: clickglassesstoreDBPROD
    MYSQL_ROOT_PASSWORD: 1q2w3e4r5%Q
    MYSQL_ROOT_HOST: '%'
    TZ: Asia/Bangkok
   restart: always
   ports:
     - 3306:3306
   volumes:
      - mysql-db:/var/lib/mysql
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
  click-glassesstore-spring-boot-app:
    container_name: clickglasses-store-spring-boot
    restart: always
    image: aiknit/project:spring-boot-clickglasses-store-spring-boot
#    build : .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    depends_on:
      - db-mysql
    links:
      - db-mysql
volumes:
  mysql-db:
