spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
googleServicesJSONFile: firebase/example-firebase-authen-firebase-adminsdk-rfcmh-d8aebfa8af.json
firebaseDatabaseUrl: https://example-firebase-authen.firebaseio.com
#firebaseStorageUrl: URL FirebaseStore if you have